name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        env:
          NODE_ENV: production
        run: pnpm build

      - name: check DB migrations
        run: |
          pnpm db:check

      - name: Trigger Vercel Production Deploy
        run: |
          curl --fail --show-error -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
